name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Use 'dist' for Vite/Vue CLI. Change to 'build' if your build script outputs elsewhere.
          branch: gh-pages # The branch the action will deploy to
